export enum DrawerCategoryType {
  WOMAN = "WOMAN",
  MAN = "MAN",
  KIDS = "KIDS",
  BEAUTY = "BEAUTY",
}

export const drawerSubCategory = [
  "NEW",
  "SPRING BREAK",
  "BEST SELLERS",
  "DRESS TIME",
  "TOPS",
  "TROUSERS",
  "SHIRTS",
  "JEANS",
  "SHORTS",
  "SKIRTS",
  "BASICS",
  "LINEN",
  "CO-ORD",
  "KNITWEAR",
  "SUITS",
  "BLAZERS",
  "ACCESSORIES",
  "PERFUMES",
  "BEAUTY",
  // "HOLIDAY EDIT",
  // "GIFT CARD",
  // "JOIN LIFE",
  // "+Info",
];
